//sampleData

const userData = [
  {
    id: "1",
    name: "Anamay Narkar",
    email: "narkaranamay@gmail.com",
    userName: "anamay123",
    password: "password123",
    profileIcon: "/assets/defaultProfileIcon.png",
    friends: [
      { id: "2", userName: "John Doe" },
      { id: "3", userName: "Jane Doe" },
      { id: "4", userName: "Alice" },
      { id: "5", userName: "Bob" },
      { id: "6", userName: "Charlie" },
      { id: "7", userName: "David" },
      { id: "8", userName: "Eve" },
      { id: "9", userName: "Frank" },
      { id: "10", userName: "Grace" },
    ],
    chatsWithFriends: [
      {
        friendUserName: "John Doe",
        friendId: "2",
        messages: [
          {
            id: "30",
            message: "Sure, let's meet at the park at 3 PM. See you there!",
            sender: "John Doe",
            time: "12:29",
            date: "2024-05-30",
          },
          {
            id: "29",
            message:
              "That sounds great! How about we meet at the park this afternoon?",
            sender: "anamay123",
            time: "12:28",
            date: "2024-05-30",
          },
          {
            id: "28",
            message:
              "I've been wanting to try that new hiking trail. Want to join me?",
            sender: "John Doe",
            time: "12:27",
            date: "2024-05-30",
          },
          {
            id: "27",
            message: "Not much, just relaxing. Any plans for the weekend?",
            sender: "anamay123",
            time: "12:26",
            date: "2024-05-30",
          },
          {
            id: "26",
            message: "Same here. What are you up to today?",
            sender: "John Doe",
            time: "12:25",
            date: "2024-05-30",
          },
          {
            id: "25",
            message: "Work's been busy, but I'm managing. How about you?",
            sender: "anamay123",
            time: "12:24",
            date: "2024-05-30",
          },
          {
            id: "24",
            message: "That's great to hear! How's work going?",
            sender: "John Doe",
            time: "12:23",
            date: "2024-05-30",
          },
          {
            id: "23",
            message:
              "Yes, it was delicious! We should go there again sometime.",
            sender: "anamay123",
            time: "12:22",
            date: "2024-05-30",
          },
          {
            id: "22",
            message:
              "Did you enjoy the new Italian restaurant we tried last week?",
            sender: "John Doe",
            time: "12:21",
            date: "2024-05-30",
          },
          {
            id: "21",
            message: "Sure, I'd be happy to help. When do you need it?",
            sender: "anamay123",
            time: "12:20",
            date: "2024-05-30",
          },
          {
            id: "20",
            message:
              "I'm working on a big project. Could you help me review it?",
            sender: "John Doe",
            time: "12:19",
            date: "2024-05-30",
          },
          {
            id: "19",
            message: "Nothing special, just catching up on some reading. You?",
            sender: "anamay123",
            time: "12:18",
            date: "2024-05-30",
          },
          {
            id: "18",
            message: "Any exciting plans for the evening?",
            sender: "John Doe",
            time: "12:17",
            date: "2024-05-30",
          },
          {
            id: "17",
            message: "That's a relief. I was worried it might be serious.",
            sender: "anamay123",
            time: "12:16",
            date: "2024-05-30",
          },
          {
            id: "16",
            message: "Just a minor cold. I'm already feeling much better.",
            sender: "John Doe",
            time: "12:15",
            date: "2024-05-30",
          },
          {
            id: "15",
            message: "Oh no! What's wrong? Are you okay?",
            sender: "anamay123",
            time: "12:14",
            date: "2024-05-30",
          },
          {
            id: "14",
            message: "I was sick last week, but I'm back in action now.",
            sender: "John Doe",
            time: "12:13",
            date: "2024-05-30",
          },
          {
            id: "13",
            message: "Haven't seen you around much lately. Everything alright?",
            sender: "anamay123",
            time: "12:12",
            date: "2024-05-30",
          },
          {
            id: "12",
            message:
              "I'm looking forward to our group's camping trip next month!",
            sender: "John Doe",
            time: "12:11",
            date: "2024-05-30",
          },
          {
            id: "11",
            message: "Same here! It's been too long since we all got together.",
            sender: "anamay123",
            time: "12:10",
            date: "2024-05-30",
          },
          {
            id: "10",
            message: "It was fun! Great to see everyone from college again.",
            sender: "John Doe",
            time: "12:09",
            date: "2024-05-30",
          },
          {
            id: "9",
            message: "How was the reunion party last Saturday?",
            sender: "anamay123",
            time: "12:08",
            date: "2024-05-30",
          },
          {
            id: "8",
            message: "Ha! I remember that. Good times!",
            sender: "John Doe",
            time: "12:07",
            date: "2024-05-30",
          },
          {
            id: "7",
            message: "Remember our coding marathon in the library?",
            sender: "anamay123",
            time: "12:06",
            date: "2024-05-30",
          },
          {
            id: "6",
            message: "Those were the days! We had so much fun in college.",
            sender: "John Doe",
            time: "12:05",
            date: "2024-05-30",
          },
          {
            id: "5",
            message: "It's been 5 years since we graduated. Time flies!",
            sender: "anamay123",
            time: "12:04",
            date: "2024-05-30",
          },
          {
            id: "4",
            message: "I'm good, thanks for asking!",
            sender: "John Doe",
            time: "12:03",
            date: "2024-05-30",
          },
          {
            id: "3",
            message: "How are you?",
            sender: "anamay123",
            time: "12:02",
            date: "2024-05-30",
          },
          {
            id: "2",
            message: "Hey Anamay!",
            sender: "John Doe",
            time: "12:01",
            date: "2024-05-30",
          },
          {
            id: "1",
            message: "Hey John!",
            sender: "anamay123",
            time: "12:00",
            date: "2024-05-30",
          },
        ],
      },
      {
        friendUserName: "Jane Doe",
        friendId: "3",
        messages: [
          {
            id: "4",
            message: "I'm good, thanks for asking!",
            sender: "Jane Doe",
            time: "12:03",
            date: "2024-05-31",
          },
          {
            id: "3",
            message: "How are you?",
            sender: "anamay123",
            time: "12:02",
            date: "2024-05-31",
          },
          {
            id: "2",
            message: "Hey Anamay!",
            sender: "Jane Doe",
            time: "12:01",
            date: "2024-05-31",
          },
          {
            id: "1",
            message: "Hey Jane!",
            sender: "anamay123",
            time: "12:00",
            date: "2024-05-31",
          },
        ],
      },
      {
        friendUserName: "Alice",
        friendId: "4",
        messages: [
          {
            id: "4",
            message: "I'm good, thanks for asking!",
            sender: "Alice",
            time: "12:03",
            date: "2024-06-01",
          },
          {
            id: "3",
            message: "How are you?",
            sender: "anamay123",
            time: "12:02",
            date: "2024-06-01",
          },
          {
            id: "2",
            message: "Hey Anamay!",
            sender: "Alice",
            time: "12:01",
            date: "2024-06-01",
          },
          {
            id: "1",
            message: "Hey Alice!",
            sender: "anamay123",
            time: "12:00",
            date: "2024-06-01",
          },
        ],
      },
      {
        friendUserName: "Bob",
        friendId: "5",
        messages: [
          {
            id: "4",
            message: "I'm good, thanks for asking!",
            sender: "Bob",
            time: "12:03",
            date: "2024-06-01",
          },
          {
            id: "3",
            message: "How are you?",
            sender: "anamay123",
            time: "12:02",
            date: "2024-06-01",
          },
          {
            id: "2",
            message: "Hey Anamay!",
            sender: "Bob",
            time: "12:01",
            date: "2024-06-01",
          },
          {
            id: "1",
            message: "Hey Bob!",
            sender: "anamay123",
            time: "12:00",
            date: "2024-06-01",
          },
        ],
      },
      {
        friendUserName: "Charlie",
        friendId: "6",
        messages: [],
      },
      {
        friendUserName: "David",
        friendId: "7",
        messages: [],
      },
      {
        friendUserName: "Eve",
        friendId: "8",
        messages: [],
      },
      {
        friendUserName: "Frank",
        friendId: "9",
        messages: [],
      },
      {
        friendUserName: "Grace",
        friendId: "10",
        messages: [],
      },
    ],
  },
];

export { userData };
